### ISSUE TITLE
Cabal flag for bytestring version

### ISSUE THREAD

**Issue by ivan-m** [haskell-hvr/cassava#157]
In 0.5.1.0, you changed the name of the flag from `pre-bytestring-0-10-4` to `bytestring--LT-0_10_4`.  Does it make sense to change flag names within the same major version release?

Also, it seems that stack doesn't like this new name:

```
Could not parse 'stack.yaml':
Aeson exception:
Error in $.flags.cassava['bytestring--LT-0_10_4']: failed to parse field 'flags': Invalid flag name: "bytestring--LT-0_10_4"
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```

**Comment by ivan-m** [comment]
Specifically, it seems that the `--` in there is what's causing the parsing issue.  Not sure why though.

**Comment by ivan-m** [comment]
It appears stack has already been fixed (albeit not in a release).

Was still a bit of a surprise to see the flag name change.

**Comment by hvr** [comment]
> Does it make sense to change flag names within the same major version release?

Well, Cabal's dependency specification deliberately doesn't allow to depend on flags of dependencies. Moreover, the flag in question was an automatic flag, i.e. you shouldn't even have any reason to manually refer to its name, as it's automatically handled by the build-tool (assuming the build-tool properly implements the Cabal spec).

**Comment by tfausak** [comment]
See #155.

**Comment by ivan-m** [comment]
@tfausak I think this issue is slightly different due to the discoverability of the flag name change.

**Comment by hvr** [comment]
I'll close this one, as I don't see much point in keeping it open. The summary is basically that the flag in question is considered an internal flag which ideally wouldn't even be exposed to the user. **It's just a technical implementation detail.** It could be any other random string over `[a-z0-9_][a-z0-9_-]*` changing with every release, it simply ought not matter which particular point in the `[a-z0-9_][a-z0-9_-]*` space is used, so it's the maintainer's prerogative to choose whichever point in that space they consider appropriate without being put on a show trial for politically motivated reasons.

**Comment by ivan-m** [comment]
Except it *isn't* internal only: as soon as you use any build tool except cabal-install (including system packagers like nix) then this flag isn't triggered correctly and the build fails with newer ghc/ bytestring,  so in practice you do need to know what the flag is.

**Comment by hvr** [comment]
Sorry, but then those build tools simply fail to implement part of the cabal specification.
