### ISSUE TITLE
Error: ‘toNamedRecord’ is not a (visible) method of class ‘ToNamedRecord’

### ISSUE THREAD

**Issue by alexander-myltsev** [haskell-hvr/cassava#173]
I'm using GHCi, version 8.6.5. The example

```haskell
data Person = Person { name :: !Text, age :: !Int }

instance ToNamedRecord Person where
    toNamedRecord (Person name age) = namedRecord [
        "name" .= name, "age" .= age]
```

Fails with the error `‘toNamedRecord’ is not a (visible) method of class ‘ToNamedRecord’`. Is that the bug? How to define it properly?

**Comment by billksun** [comment]
Just hit this error myself. @alexander-myltsev did you ever find a solution for this?

**Comment by andreasabel** [comment]
Then I take this as the answer!
