### ISSUE TITLE
flag bytestring--LT-0_10_4 default

### ISSUE THREAD

**Issue by robwithhair** [haskell-hvr/cassava#183]
https://github.com/haskell-hvr/cassava/blob/5996d4f6c6a88dbb77788d7583ed6f1c1ed90b38/cassava.cabal#L53

This flag is locking ByteString package down to 0.10.4 by default.  This is beginning to create problems with other packages.  Tests pass when this flag is set to false.  Should this flag be default be false?

Not knowing the history of this flag it is difficult for me to know how to set it.  Perhaps the documentation needs an update with a more full description to avoid future user confusion?

**Comment by andreasabel** [comment]
> Should this flag be default be false?

Yes, absolutely!

**Comment by andreasabel** [comment]
Fix by 0.5.2.0-r6: https://hackage.haskell.org/package/cassava-0.5.2.0/revisions/
