### ISSUE TITLE
Doesn't work with bytestring-0.10.12.0

### ISSUE THREAD

**Issue by JivanRoquet** [haskell-hvr/cassava#196]
Hello,

Adding this to `stack.yaml`:

```yaml
extra-deps:
  - cassava-0.5.2.0        # this is the new bit
  - bytestring-0.10.12.0   # was previously already there
```

leads to the following error on `stack build`:

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for cassava-0.5.2.0:
    bytestring-0.10.12.0 from stack configuration does not match >=0.9.2 && <0.10.4  (latest matching version is 0.10.2.0)
needed due to myproj -> cassava-0.5.2.0
```

Setting `bytestring-0.10.2.0` in `stack.yaml` creates a huge mess in the whole project.

Is there any way around this?

**Comment by andreasabel** [comment]
cassava-0.5.2.0 has been revised to allow the latest bytestring.  Issue should be fixed as soon as Stackage picks up the latest revision (r5).
