### ISSUE TITLE
base version mismatch in 0.5.2.0

### ISSUE THREAD

**Issue by yaitskov** [haskell-hvr/cassava#200]
Hackage page states requirement base less than 4.16 but compilation fails with:
```
  cassava = dontCheck (fromHackage {
    pkg = "cassava";
    ver = "0.5.2.0";
    sha256 = "15mnkix11y3fg6shyrrs50yix9alkyikzyld8jkbkldxm98c49g8";
  } {});

```

```
Setup: Encountered missing or private dependencies:
base >=4.5 && <4.14
```

I run ghc-8.10.4

**Comment by yaitskov** [comment]
master builds without problems:

```
  sources.cassava = pkgs.fetchFromGitHub {
    owner = "haskell-hvr";
    repo = "cassava";
    rev = "2348030aec2a19f12a633bf553bf81ff59be37a5";
    sha256 = "11zm3ismvy9kpqphh3lpxvgy595fs7arnjvgkzvl54lhyh71gfzl";
  };

``` 

I don't see tag 0.5.2.0 on github.
So I guess hackage is somehow corrupted.

**Comment by andreasabel** [comment]
There is a tag 0.5.2.0 on github now.
Note that 0.5.2.0 has been revised on hackage several times to make it build in an updated ecosystem: https://hackage.haskell.org/package/cassava-0.5.2.0/revisions/
I don't know what `fromHackage` does, but if it only gets the original tarball, the revisions will not be included, and it won't work.  In contrast `cabal get` also retrieves the revisions and patches the cabal file after unpacking the tarball.
