### ISSUE TITLE
Not enough instances for tuples

### ISSUE THREAD

**Issue by bos** [haskell-hvr/cassava#59]
I just tried to write out a 9-tuple and failed because there's not a predefined instance.

**Comment by timbod7** [comment]
I just needed a 10 tuple.

Based upon the haskell report  section 6.1.4 (https://www.haskell.org/onlinereport/basic.html#basic-tuples) it would seem to make sense to support up to 15 tuples?

**Comment by tibbe** [comment]
Lets do 15. Could you please make a pull request?
