### ISSUE TITLE
Provide a type class-less encoding and decoding based API

### ISSUE THREAD

**Issue by tibbe** [haskell-hvr/cassava#67]
Noah Daniels writes:

> I have the following, which assumes that each record will be of length 25:
> 
> ``` haskell
> instance FromRecord Barcode where
>     parseRecord v
>         | V.length v == 25 = Barcode <$>
>                              v .! 0  <*>
>                              T.traverse parseField (V.tail v)
>         | otherwise        = mzero
> ```
> 
> I'd like to parameterize this length, so that it can be run on datasets that might have barcodes of different lengths. But, I want to make sure that for a given data set, all barcodes are the same length. One way to do this is to infer that length from the first record in the input file; the other way is to require it as a parameter. I'm ok with either option. In some ways, I prefer requiring it as a parameter, as it keeps the biologists honest :)
> 
> I realize this gets into dependent types, which Haskell doesn't really support. Other than the obvious and awful solution of post-processing all the records and yelling at the user if he or she gives bad input, is there any nice way to make parseRecord take the record length as a parameter? Either compile-time or run-time would be acceptable.

I think we could support this by adding a different decode function

``` haskell
decodeUsing :: (Record -> Parser a) -> HasHeader -> ByteString -> Either String (Vector a)
```

You could then pass in an arbitrary parsing function, including a parameterized one. Here's one possible such function, assuming that you already have a `FromRecord` instance for `a` and just want to do some sanity checking:

``` haskell
decodeBarcode :: Int -> Record -> Parser a
decodeBarcode n v
    | V.length v - 1 /= n = mzero
    | otherwise           = parseRecord v
```

You'd use it like so

``` haskell
test = decodeUsing (decodeBarcode someLength) ...
```

**Comment by jb55** [comment]
Shouldn't this be as easy as exposing decodeWithP? I really need this as well. Let me know if that makes sense and I'll submit a PR.

**Comment by tibbe** [comment]
Yes in principle. I wanted to do some remaining as well. I will try to do it during ICFP.
